#!/bin/bash -e

host=${host:-http://cfconrad-vm.qa.suse.de}

if [[ $# -eq 0 ]]; then
    echo "Get all job ID's belonging to one product post and delete each of them."
    echo "This is usefull, if you did a isos post with wrong parameters and trirggered"
    echo "to many products."
    echo "Default host is $host."
    echo ""
    echo "Usage:"
    echo "  openqa-isos-post-revert <product-post-number>"
    echo "  host=https://openqa.suse.de openqa-isos-post-revert <product-post-number>"
    exit 2;
fi


PRODUCT_POSTS="$*"

for i in $PRODUCT_POSTS; do
  openqa-cli api -X GET -host "$host" "isos/$i" | \
  jq -r '.results.successful_job_ids[] , .results.failed_job_info[].job_id | if type=="array" then .[] else . end' | sort | uniq | \
  xargs -I {} openqa-cli api --host "$host" -X DELETE jobs/{}
done
