#!/bin/bash -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$SCRIPT_DIR/.vault_include"

OUTFILE=${1:-gce_credentials.json}

vault_login;

RES=$(vault read "${VAULT_NAMESPACE}/gcp/key/openqa-role" -format=json)
LEASE_ID=$(echo "${RES}" | jq -r '.lease_id')

echo "${RES}" | jq -r '.data.private_key_data' | base64 -d > "${OUTFILE}"

echo "--------------------------------"
echo "Outputfile: ${OUTFILE}"
echo "--------------------------------"
echo "# Revoke with:"
echo "curl --header 'X-Vault-Token: $VAULT_TOKEN'  --request POST --data '{\"lease_id\":\"${LEASE_ID}\"}' ${VAULT_ADDR}/v1/sys/leases/revoke" | tee -a ~/.vault_leases

echo "--------------------------------"
echo " gcloud login:"
echo "gcloud auth activate-service-account --key-file=${OUTFILE} --project=\$(jq -r '.project_id' ${OUTFILE})"
